### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [jkergal/hyperjs-wsl-zsh-powerlevel10k-terminal-config#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), there are currently no windows-specific setup links and this would make a good start.  However, it doesn't have a license file - could you please add one?

If you don't have a specific license in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by jkergal** [comment]
Hi Joe! Sorry for the delay of the response!

I'll do it quickly, thank's for your interest !

**Comment by jkergal** [comment]
> I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), there are currently no windows-specific setup links and this would make a good start. However, it doesn't have a license file - could you please add one?
> 
> If you don't have a specific license in mind, I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.
> 
> Thanks!

That's done! :)

Glad that you want you add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins) so it can help the community!

**Comment by unixorn** [comment]
Thanks!

**Comment by jkergal** [comment]
Thanks to you!
